projects:
  - id: "test1"
    name: "Testing One"
    url: "https://example.org"
    channel: "https://leangeder.slack.com/messages/CD8KHAKA8"
    qa: ["QA ID 1", "QA ID 2"]
    owners: ["Owner ID 1", "Owner ID 2"]
  - id: "test2"
    name: "Testing Two"
    url: "https://example.org"
    channel: "ChannelID"
    qa: ["QA ID 1", "QA ID 2"]
    owners: ["Owner ID 1", "Owner ID 2"]
