---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatops2
  labels:
    app: chatops2
    component: chatops2
    role: services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chatops2
        component: chatops2
        role: services
    spec:
      containers:
      - name: chatops2
        image: {{.esimage}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /metrics
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
          # resources:
          #   requests:
          #     memory: "{{.esclient.memory}}"
          #   limits:
          #     memory: "{{.esclient.memory}}"
          # env:
          # - name: NAMESPACE
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: metadata.namespace
          # - name: NODE_NAME
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: metadata.name
        ports:
        - containerPort: 8080
          name: http
      #   volumeMounts:
      #   - name: elasticconfig
      #     mountPath: /elasticsearch/config/log4j2.properties
      #     subPath: log4j2.properties
      # volumes:
      # - name: elasticconfig
      #   configMap:
      #     name: elasticconfig
      # - name: commonstorage
      #   secret:
      #     secretName: certs
