---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cerebro
  namespace: {{.namespace}}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: beamery-cerebro-ip
    kubernetes.io/ingress.allow-http: "false"
  labels:
    app: cerebro
    component: elasticsearch
    role: tool
spec:
  tls:
  - secretName: support-tls
  rules:
  - host: cerebro.support.beamery.com
    http:
      paths:
      - backend:
          serviceName: cerebro-ro
          servicePort: http
  - host: cerebro.admin.beamery.com
    http:
      paths:
      - backend:
          serviceName: cerebro-rw
          servicePort: http
